services:
  - type: static_site
    name: userportal
    repo: ujjwal-kriti/userdashboards
    branch: main
    buildCommand: "npm run build"
    publishPath: "dist"
    env:
      - key: NODE_VERSION
        value: "18"
